config/routes.rb
BetaRules::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'blogs#index'

  resources :blogs, only: :index do
    member do
      get 'follow_blog', as: 'follow'
      get 'unfollow_blog', as: 'unfollow'
      get 'post_comment', as: 'post_comment'
      get 'delete_comment', as: 'delete_comment'
      get 'like_comment', as: 'like_comment'
      get 'unlike_comment', as: 'unlike_comment'
    end
  end

  namespace :admin do
    resources :categories do
      get :get_sub_categories , on: :collection
      get :sub_categories_dropdown , on: :collection
    end
  end
  get '/:year/:month/:day/:id' => 'blogs#show', constraints: {
    year:  /\d{4}/,
    month: /\d{1,2}/,
    day:  /\d{1,2}/
  }, as: 'blog'

  resources :categories, only: :show
  resources :tags, only: :show
  resources :users

  get '/login' => 'users#login', as: 'login'
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', to: redirect('/')
  match '/signout', to: 'sessions#destroy', as: 'signout'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :slug, :title

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_and_belongs_to_many :blogs

  validates :title, presence: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag ||= Tag.find_by_slug(params[:id])
    @left_blogs ||= @tag.blogs.text_search(params[:query]).order('visitors_count desc').page(params[:page]).per_page(5) if @tag.present?
    @center_blogs ||= @tag.blogs.text_search(params[:query]).order('created_at desc').page(params[:page]).per_page(5) if @tag.present?
    @right_blogs ||= @tag.blogs.text_search(params[:query]).sort_by_comments.page(params[:page]).per_page(5) if @tag.present?
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_center_blogs.html.erb
  <% blogs.each do |blog| %>
    <div class='blog-holder'>
      <ul class='thumbnails'>
        <li class='span12'>
          <%= link_to image_tag(blog.main_pic.url(:medium), width: '100%'), blog_path(blog.created_at.strftime('%Y'), blog.created_at.strftime('%m'), blog.created_at.strftime('%d'), blog.slug) if blog.main_pic.present? %>
        </li>
        <div class='row-fluid'>
          <div class='span12 blog-category'>
            <%= link_to blog.category.title.upcase, category_path(blog.category.slug) if blog.category.present? %>
          </div>
        </div>
        <div class='row-fluid blog-title'>
          <div class='span12'>
            <%= link_to blog.title, blog_path(blog.created_at.strftime('%Y'), blog.created_at.strftime('%m'), blog.created_at.strftime('%d'), blog.slug) if blog.title.present? %>
          </div>
        </div>
        <div class='row-fluid blog-sharing'>
          <div class='span12'>
            <a href='javascript:void(0);'>
              <span class='st_facebook_hcount' displayText='Share' st_title="<%= blog.title %>" st_url="<%= blog_url(blog.created_at.strftime('%Y'), blog.created_at.strftime('%m'), blog.created_at.strftime('%d'), blog.slug) %>" st_summary="<%= short_description(blog.description) if blog.description.present? %>" st_image="<%= blog.main_pic.url if blog.main_pic.present? %>"></span>
              <span class='st_twitter_hcount' displayText='Tweet' st_title="<%= blog.title %>" st_url="<%= blog_url(blog.created_at.strftime('%Y'), blog.created_at.strftime('%m'), blog.created_at.strftime('%d'), blog.slug) %>" st_summary="<%= short_description(blog.description) if blog.description.present? %>" st_image="<%= blog.main_pic.url if blog.main_pic.present? %>"></span>
              <span class='st_googleplus_hcount' displayText='Share' st_title="<%= blog.title %>" st_url="<%= blog_url(blog.created_at.strftime('%Y'), blog.created_at.strftime('%m'), blog.created_at.strftime('%d'), blog.slug) %>" st_summary="<%= short_description(blog.description) if blog.description.present? %>" st_image="<%= blog.main_pic.url if blog.main_pic.present? %>"></span>
            </a>
          </div>
        </div>
      </ul>
    </div>
  <% end %>

  <%= will_paginate @center_blogs %>

app/views/tags/_left_blogs.html.erb
  <% blogs.each do |blog| %>
    <div class='left-blog-holder'>
      <div class='row-fluid'>
        <div class='span3'>
          <ul class='thumbnails'>
            <li class='span12'>
              <%= link_to image_tag(blog.main_pic.url(:small), width: '100%'), blog_path(blog.created_at.strftime('%Y'), blog.created_at.strftime('%m'), blog.created_at.strftime('%d'), blog.slug) if blog.main_pic.present? %>
            </li>
          </ul>
        </div>
        <div class='span9'>
          <div class='row-fluid blog-title'>
            <div class='span12'>
              <%= link_to blog.title.upcase, blog_path(blog.created_at.strftime('%Y'), blog.created_at.strftime('%m'), blog.created_at.strftime('%d'), blog.slug) if blog.title.present? %>
            </div>
          </div>
          <div class='row-fluid left-blog-sharing'>
            <div class='span12'>
              <a href='javascript:void(0);'>
                <span class='st_sharethis_hcount' displayText='Share' st_title="<%= blog.title %>" st_url="<%= blog_url(blog.created_at.strftime('%Y'), blog.created_at.strftime('%m'), blog.created_at.strftime('%d'), blog.slug) %>" st_summary="<%= short_description(blog.description) if blog.description.present? %>" st_image="<%= blog.main_pic.url if blog.main_pic.present? %>"></span> / <%= last_updated_at(blog.updated_at) %>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <%= will_paginate @left_blogs %>

app/views/tags/_right_blogs.html.erb
  <% blogs.each do |blog| %>
    <div class='blog-holder'>
      <ul class='thumbnails'>
        <li class='span12'>
          <%= link_to image_tag(blog.main_pic.url(:large), width: '100%'), blog_path(blog.created_at.strftime('%Y'), blog.created_at.strftime('%m'), blog.created_at.strftime('%d'), blog.slug) if blog.main_pic.present? %>
          <div class='row-fluid blog-category'>
            <div class='span12'>
              <%= link_to blog.category.title.upcase, category_path(blog.category.slug) if blog.category.present? %>
            </div>
          </div>
          <div class='row-fluid blog-title'>
            <div class='span12'>
              <%= link_to blog.title, blog_path(blog.created_at.strftime('%Y'), blog.created_at.strftime('%m'), blog.created_at.strftime('%d'), blog.slug) if blog.title.present? %>
            </div>
          </div>
          <div class='row-fluid blog-description'>
            <div class='span12'>
              <%= short_description(blog.description) if blog.description.present? %>
            </div>
          </div>
          <div class='row-fluid blog-sharing'>
            <div class='span12'>
              <a href='javascript:void(0);'>
                <span class='st_facebook_hcount' displayText='Share' st_title="<%= blog.title %>" st_url="<%= blog_url(blog.created_at.strftime('%Y'), blog.created_at.strftime('%m'), blog.created_at.strftime('%d'), blog.slug) %>" st_summary="<%= short_description(blog.description) if blog.description.present? %>" st_image="<%= blog.main_pic.url if blog.main_pic.present? %>"></span>
                <span class='st_twitter_hcount' displayText='Tweet' st_title="<%= blog.title %>" st_url="<%= blog_url(blog.created_at.strftime('%Y'), blog.created_at.strftime('%m'), blog.created_at.strftime('%d'), blog.slug) %>" st_summary="<%= short_description(blog.description) if blog.description.present? %>" st_image="<%= blog.main_pic.url if blog.main_pic.present? %>"></span>
                <span class='st_googleplus_hcount' displayText='Share' st_title="<%= blog.title %>" st_url="<%= blog_url(blog.created_at.strftime('%Y'), blog.created_at.strftime('%m'), blog.created_at.strftime('%d'), blog.slug) %>" st_summary="<%= short_description(blog.description) if blog.description.present? %>" st_image="<%= blog.main_pic.url if blog.main_pic.present? %>"></span>
              </a>
            </div>
          </div>
        </li>
      </ul>
    </div>
  <% end %>

  <%= will_paginate @right_blogs %>

app/views/tags/show.html.erb
<%- model_class = Category -%>

<div class='row-fluid'>
  <div class='span12'>
    <hgroup class="hgroup">
      <h2>
        <%=t '.title', :default => @tag.title.titleize if @tag.present? %>
      </h2>
    </hgroup>
  </div>
</div>

<div class='row-fluid'>
  <div class="span3 left_blogs_container">
    <div class='row-fluid'>
      <div class='span12 mostviewedhead'>
        <h5>Hot Topics</h5>
      </div>
    </div>

    <div id='left_side_blogs' class='mostviewed'>
      <%= render '/blogs/left_blogs', :blogs => @left_blogs %>
    </div>
  </div><!--/span-->

  <div class="span4 center_blogs_container">
    <div class='row-fluid'>
      <div class='span12 mostrecenthead'>
        <h5><%= image_tag(asset_path('coffee_break.png'), width: '16px') %> Coffee Break</h5>
      </div>
    </div>

    <div id='/blogs/center_blogs' class='mostrecent'>
      <%= render '/blogs/center_blogs', :blogs => @center_blogs %>
    </div>
  </div><!--/span-->

  <div class="span5 right_blogs_container">
    <div class='row-fluid'>
      <div class='span12 mostpopularhead'>
        <h5>Check this out</h5>
      </div>
    </div>

    <div id='right_side_blogs' class='mostpopular'>
      <%= render '/blogs/right_blogs', :blogs => @right_blogs %>
    </div>
  </div>
</div>

app/views/tags/show.js.erb
$('#left_side_blogs').append("<%= j render '/blogs/left_blogs', :blogs => @left_blogs %>")
$('#center_blogs').append("<%= j render '/blogs/center_blogs', :blogs => @center_blogs %>")
$('#right_side_blogs').append("<%= j render '/blogs/right_blogs', :blogs => @right_blogs %>")

<% if @left_blogs.next_page %>
  $('#left_side_blogs .pagination').replaceWith('<%= j will_paginate(@left_blogs) %>');
<% else %>
  $('#left_side_blogs .pagination').remove();
<% end %>

<% if @center_blogs.next_page %>
  $('#center_blogs .pagination').replaceWith('<%= j will_paginate(@center_blogs) %>');
<% else %>
  $('#center_blogs .pagination').remove();
<% end %>

<% if @right_blogs.next_page %>
  $('#right_side_blogs .pagination').replaceWith('<%= j will_paginate(@right_blogs) %>');
<% else %>
  $('#right_side_blogs .pagination').remove();
<% end %>